# Generated by Django 4.1.4 on 2022-12-31 16:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('data_Publication', models.DateTimeField(default=datetime.datetime.now)),
                ('type_ai', models.CharField(choices=[('Terrain', 'Terrain'), ('Terrain_Agricole', 'Terrain Agricole'), ('Appartement', 'Appartement'), ('Maison', 'Maison'), ('Bungalow', 'Bungalow')], max_length=50)),
                ('category', models.CharField(choices=[('Vente', 'Vente'), ('Echange', 'Echange'), ('Location', 'Location')], max_length=50)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('information_name', models.CharField(max_length=50)),
                ('information_tel', models.IntegerField()),
                ('information_email', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
