# Generated by Django 4.1.4 on 2022-12-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_useraccount_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
