# Generated by Django 4.1.4 on 2023-01-03 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ai_rename_name_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
