# Generated by Django 4.1.4 on 2023-01-03 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aiimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='aiimage',
            name='ai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.ai'),
        ),
    ]
