# Generated by Django 4.1.4 on 2023-01-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_images_ai_image_alter_aiimage_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='description',
            field=models.TextField(),
        ),
    ]
